/scratch/ptolemy/users/kg1623/projects/deep-learning/audio-classification-using-ViT/venv/lib/python3.10/site-packages/torch_audiomentations/core/transforms_interface.py:76: FutureWarning: Transforms now expect an `output_type` argument that currently defaults to 'tensor', will default to 'dict' in v0.12, and will be removed in v0.13. Make sure to update your code to something like:
  >>> augment = Gain(..., output_type='dict')
  >>> augmented_samples = augment(samples).samples
  warnings.warn(
/scratch/ptolemy/users/kg1623/projects/deep-learning/audio-classification-using-ViT/venv/lib/python3.10/site-packages/torch_audiomentations/core/transforms_interface.py:76: FutureWarning: Transforms now expect an `output_type` argument that currently defaults to 'tensor', will default to 'dict' in v0.12, and will be removed in v0.13. Make sure to update your code to something like:
  >>> augment = AddColoredNoise(..., output_type='dict')
  >>> augmented_samples = augment(samples).samples
  warnings.warn(
/scratch/ptolemy/users/kg1623/projects/deep-learning/audio-classification-using-ViT/venv/lib/python3.10/site-packages/torch_audiomentations/core/transforms_interface.py:76: FutureWarning: Transforms now expect an `output_type` argument that currently defaults to 'tensor', will default to 'dict' in v0.12, and will be removed in v0.13. Make sure to update your code to something like:
  >>> augment = PitchShift(..., output_type='dict')
  >>> augmented_samples = augment(samples).samples
  warnings.warn(
/scratch/ptolemy/users/kg1623/projects/deep-learning/audio-classification-using-ViT/venv/lib/python3.10/site-packages/torch_audiomentations/core/transforms_interface.py:76: FutureWarning: Transforms now expect an `output_type` argument that currently defaults to 'tensor', will default to 'dict' in v0.12, and will be removed in v0.13. Make sure to update your code to something like:
  >>> augment = Shift(..., output_type='dict')
  >>> augmented_samples = augment(samples).samples
  warnings.warn(
Using the latest cached version of the dataset since danavery/urbansound8K couldn't be found on the Hugging Face Hub
Found the latest cached dataset configuration 'default' at /scratch/ptolemy/users/kg1623/.cache/huggingface/datasets/danavery___urbansound8_k/default/0.0.0/8aa9177a0c5a6949ee4ee4b7fcabb01dfd4ae466 (last modified on Sat Apr 26 19:45:24 2025).
  0%|          | 0/100 [00:00<?, ?it/s]  1%|          | 1/100 [01:24<2:19:18, 84.43s/it]  2%|▏         | 2/100 [02:43<2:12:59, 81.43s/it]  3%|▎         | 3/100 [04:03<2:10:31, 80.74s/it]  4%|▍         | 4/100 [05:37<2:17:16, 85.79s/it]  5%|▌         | 5/100 [06:55<2:11:16, 82.91s/it]  6%|▌         | 6/100 [08:15<2:08:49, 82.22s/it]  7%|▋         | 7/100 [09:36<2:06:42, 81.74s/it]  8%|▊         | 8/100 [10:54<2:03:40, 80.66s/it]  9%|▉         | 9/100 [12:15<2:02:16, 80.62s/it] 10%|█         | 10/100 [13:41<2:03:30, 82.34s/it] 11%|█         | 11/100 [15:01<2:01:04, 81.62s/it] 12%|█▏        | 12/100 [16:35<2:05:02, 85.25s/it] 13%|█▎        | 13/100 [17:50<1:59:07, 82.15s/it] 14%|█▍        | 14/100 [19:27<2:04:08, 86.62s/it] 15%|█▌        | 15/100 [20:43<1:58:21, 83.55s/it] 16%|█▌        | 16/100 [22:00<1:53:57, 81.40s/it] 17%|█▋        | 17/100 [23:18<1:51:25, 80.54s/it] 18%|█▊        | 18/100 [24:36<1:49:04, 79.81s/it] 19%|█▉        | 19/100 [25:53<1:46:25, 78.84s/it] 20%|██        | 20/100 [27:17<1:47:19, 80.49s/it] 21%|██        | 21/100 [28:43<1:47:59, 82.02s/it] 22%|██▏       | 22/100 [30:01<1:45:03, 80.81s/it] 23%|██▎       | 23/100 [31:18<1:42:20, 79.74s/it] 24%|██▍       | 24/100 [32:38<1:41:16, 79.95s/it] 25%|██▌       | 25/100 [33:56<1:38:59, 79.19s/it] 26%|██▌       | 26/100 [35:13<1:37:05, 78.72s/it] 27%|██▋       | 27/100 [36:56<1:44:30, 85.90s/it] 28%|██▊       | 28/100 [38:16<1:40:59, 84.17s/it] 29%|██▉       | 29/100 [39:36<1:37:52, 82.71s/it] 29%|██▉       | 29/100 [40:53<1:40:07, 84.62s/it]
/scratch/ptolemy/users/kg1623/projects/deep-learning/audio-classification-using-ViT/venv/lib/python3.10/site-packages/torch/__init__.py:2150: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert condition, message
